src/Entity/Invoice.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\InvoiceRepository")
 */
class Invoice
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="invoices")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $paid;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_paid;

    /**
     * @ORM\Column(type="float")
     */
    private $total;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getPaid(): ?bool
    {
        return $this->paid;
    }

    public function setPaid(bool $paid): self
    {
        $this->paid = $paid;

        return $this;
    }

    public function getDatePaid(): ?\DateTimeInterface
    {
        return $this->date_paid;
    }

    public function setDatePaid(\DateTimeInterface $date_paid): self
    {
        $this->date_paid = $date_paid;

        return $this;
    }

    public function __toString()
    {
        return (string) $this->getId();
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(float $total): self
    {
        $this->total = $total;

        return $this;
    }
}

src/Form/InvoiceType.php
<?php

namespace App\Form;

use App\Entity\Invoice;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InvoiceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date')
            ->add('paid')
            ->add('date_paid')
            ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Invoice::class,
        ]);
    }
}

src/Controller/InvoiceController.php
<?php

namespace App\Controller;

use App\Entity\Invoice;
use App\Form\InvoiceType;
use App\Repository\InvoiceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/invoice")
 */
class InvoiceController extends AbstractController
{
    /**
     * @Route("/", name="invoice_index", methods={"GET"})
     */
    public function index(InvoiceRepository $invoiceRepository): Response
    {
        return $this->render('invoice/index.html.twig', [
            'invoices' => $invoiceRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="invoice_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $invoice = new Invoice();
        $form = $this->createForm(InvoiceType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($invoice);
            $entityManager->flush();

            return $this->redirectToRoute('invoice_index');
        }

        return $this->render('invoice/new.html.twig', [
            'invoice' => $invoice,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="invoice_show", methods={"GET"})
     */
    public function show(Invoice $invoice): Response
    {
        return $this->render('invoice/show.html.twig', [
            'invoice' => $invoice,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="invoice_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Invoice $invoice): Response
    {
        $form = $this->createForm(InvoiceType::class, $invoice);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('invoice_index', [
                'id' => $invoice->getId(),
            ]);
        }

        return $this->render('invoice/edit.html.twig', [
            'invoice' => $invoice,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="invoice_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Invoice $invoice): Response
    {
        if ($this->isCsrfTokenValid('delete'.$invoice->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($invoice);
            $entityManager->flush();
        }

        return $this->redirectToRoute('invoice_index');
    }
}

templates/invoice/_delete_form.html.twig
<form method="post" action="{{ path('invoice_delete', {'id': invoice.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ invoice.id) }}">
    <button class="btn">Delete</button>
</form>

templates/invoice/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/invoice/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Invoice{% endblock %}

{% block body %}
    <h1>Edit Invoice</h1>

    {{ include('invoice/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('invoice_index') }}">back to list</a>

    {{ include('invoice/_delete_form.html.twig') }}
{% endblock %}

templates/invoice/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Invoice index{% endblock %}

{% block body %}
    <h1>Invoice index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Paid</th>
                <th>Date_paid</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for invoice in invoices %}
            <tr>
                <td>{{ invoice.id }}</td>
                <td>{{ invoice.date ? invoice.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ invoice.paid ? 'Yes' : 'No' }}</td>
                <td>{{ invoice.datePaid ? invoice.datePaid|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('invoice_show', {'id': invoice.id}) }}">show</a>
                    <a href="{{ path('invoice_edit', {'id': invoice.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('invoice_new') }}">Create new</a>
{% endblock %}

templates/invoice/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Invoice{% endblock %}

{% block body %}
    <h1>Create new Invoice</h1>

    {{ include('invoice/_form.html.twig') }}

    <a href="{{ path('invoice_index') }}">back to list</a>
{% endblock %}

templates/invoice/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Invoice{% endblock %}

{% block body %}
    <h1>Invoice</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ invoice.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ invoice.date ? invoice.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Paid</th>
                <td>{{ invoice.paid ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Date_paid</th>
                <td>{{ invoice.datePaid ? invoice.datePaid|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('invoice_index') }}">back to list</a>

    <a href="{{ path('invoice_edit', {'id': invoice.id}) }}">edit</a>

    {{ include('invoice/_delete_form.html.twig') }}
{% endblock %}