src/Entity/Row.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RowRepository")
 */
class Row
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Invoice", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $invoice;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Product")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Product;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInvoice(): ?Invoice
    {
        return $this->invoice;
    }

    public function setInvoice(?Invoice $invoice): self
    {
        $this->invoice = $invoice;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->Product;
    }

    public function setProduct(?Product $Product): self
    {
        $this->Product = $Product;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }
}

src/Entity/User.php
<?php
// src/Entity/User.php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Invoice", mappedBy="user")
     */
    private $invoices;

    public function __construct()
    {
        parent::__construct();
        $this->invoices = new ArrayCollection();
        // your own logic
    }

    /**
     * @return Collection|Invoice[]
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): self
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices[] = $invoice;
            $invoice->setUser($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): self
    {
        if ($this->invoices->contains($invoice)) {
            $this->invoices->removeElement($invoice);
            // set the owning side to null (unless already changed)
            if ($invoice->getUser() === $this) {
                $invoice->setUser(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return (string) $this->getUsername();
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Invoice;
use App\Entity\Row;
use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{
    /**
     * @Route("/profile/dashboard", name="user")
     */
    public function index()
    {
        $id = $this->container->get('security.token_storage')->getToken()->getUser();

        $user = $this->getDoctrine()
            ->getRepository(User::class)
            ->find($id->getId());

        $invoice = $this->getDoctrine()
            ->getRepository(Invoice::class)
            ->findBy(['user' => $id->getId()]);

        return $this->render('user/index.html.twig', [
            'user' => $user,
            'invoice' => $invoice
        ]);
    }

    /**
     * @Route("/profile/dashboard/invoice/check/{id}/", name="user_see_invoice")
     */
    public function seeInvoiceAction($id){
        $invoice = $this->getDoctrine()
            ->getRepository(Invoice::class)
            ->findBy(['id' => $id]);

        $row = $this->getDoctrine()
            ->getRepository(Row::class)
            ->findBy(['invoice' => $id]);

        return $this->render('user/see_own_invoice.html.twig', [
            'invoice' => $invoice,
            'row' => $row
        ]);
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    Invoices for {{ user }}<br>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">Invoice date</th>
            <th scope="col">Payment date</th>
            <th scope="col">Payment status</th>
            <th scope="col">Total paid</th>
        </tr>
        </thead>
        <tbody>
        {% for invoice in invoice %}
        <tr>
            <td scope="row">{{ invoice.date|date('d-m-Y') }}</td>
            <td>{{ invoice.datepaid|date('d-m-Y') }}</td>
            <td>{% if invoice.paid == 1 %}Paid{% else %}Not paid {% endif %}</td>
            <td>€{{ invoice.total }}</td>
            <td><a href="{{ path('user_see_invoice', {id : invoice.id}) }}" class="btn btn-success pull-right">See invoice</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/user/see_own_invoice.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="example-wrapper">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Product description</th>
                <th scope="col">Product price</th>
                <th scope="col">Product quantity</th>
                <th scope="col">Product total</th>
            </tr>
            </thead>
            <tbody>
            {% for row in row %}
                <tr>
                    <td>{{ row.product.description }}</td>
                    <td>€{{ row.product.price }}</td>
                    <td>{{ row.quantity }}</td>
                    <td>€{{ row.quantity * row.product.price }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>


        <table class="table">
            <thead>
            <tr>
                <th scope="col">Invoice date</th>
                <th scope="col">Payment date</th>
                <th scope="col">Payment status</th>
                <th scope="col">Total paid</th>
            </tr>
            </thead>
            <tbody>
            {% for invoice in invoice %}
                <tr>
                    <td scope="row">{{ invoice.date|date('d-m-Y') }}</td>
                    <td>{{ invoice.datepaid|date('d-m-Y') }}</td>
                    <td>{% if invoice.paid == 1 %}Paid{% else %}Not paid {% endif %}</td>
                    <td>€{{ invoice.total }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}